server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/customers/**
          filters:
          - StripPrefix=1
        - id: account-service
          uri: http://localhost:8083
          predicates:
          - Path=${app.api-prefix}/accounts/**
          filters:
          - StripPrefix=1
        - id: audit-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/audit/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: file_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=1
